language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  
virtualenv:

# command for running tests
script: pytest

after_success:
- coveralls
